---
- name: Parchado servidores
  hosts: acs_db,acs_manager,acs_nfs
  become: yes
  gather_facts: yes

  tasks:
    - name: Actualizar todos los paquetes (Cualquier versión de Rocky/RHEL)
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      register: dnf_result

    - name: Crear log de actualización en /tmp/update_history.txt
      copy:
        dest: /tmp/update_history.txt
        content: |
          ==================================================
          REPORTE DE ACTUALIZACIÓN ANSIBLE
          ==================================================
          Fecha:      {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          Servidor:   {{ inventory_hostname }}
          S.O.:       {{ ansible_distribution }} {{ ansible_distribution_version }}
          Estado:     {{ 'SISTEMA ACTUALIZADO' if dnf_result.changed else 'SIN CAMBIOS' }}
          
          PAQUETES PROCESADOS:
          {% if dnf_result.results is defined %}
          {{ dnf_result.results | join('\n') }}
          {% else %}
          Ninguno (El sistema ya estaba al día).
          {% endif %}
          ==================================================
        owner: root
        group: root
        mode: '0644'
      
      when: dnf_result is defined

    - name: Verificar si se requiere reiniciar (needs-restarting)
      shell: "needs-restarting -r"
      register: reboot_required
      ignore_errors: yes
      failed_when: false
      changed_when: false

    - name: Reiniciar el servidor si el kernel o librerías cambiaron
      reboot:
        msg: "Reinicio automático por parcheo de seguridad (Ansible)"
        reboot_timeout: 600
      when: reboot_required.rc is defined and reboot_required.rc != 0